### PR TITLE
Report UpstreamGone.

### LINKED ISSUE #19: Upstream Gone
https://github.com/dahlbyk/posh-git/pull/326 added support for Gone branch status, which is missing from this cache response. I'd suggest a boolean `UpstreamGone` property.

To reproduce (assuming origin/gone doesn't exist):

```
> git branch gone
> git config branch.gone.remote origin
> git config branch.gone.merge refs/heads/gone
> git checkout gone
Switched to branch 'gone'
Your branch is based on 'origin/gone', but the upstream is gone.
  (use "git branch --unset-upstream" to fixup)
```

### PR DESCRIPTION
**Pull request by cmarcusreid**
Report UpstreamGone. Resolves #19.

UpstreamGone is set when a branch has no remote tracking reference but still has an upstream configured. This is similar to the git warning:

Your branch is based on 'origin/master', but the upstream is gone.
  (use "git branch --unset-upstream" to fixup)

### CODE REVIEW

**Comment by cmarcusreid** [comment]
Reading side for posh-git is https://github.com/cmarcusreid/posh-git/commit/4fa6c8c74a8c90a7777bb217aec5f370aca0ee89. I'll submit a PR there once this is merged and the new executable is published.

**Comment by DoCode** [comment]
@cmarcusreid, can you please update libgit to the latest release?

**Comment by cmarcusreid** [comment]
@DoCode I've previously had some functionality issues when upgrading libgit2, so I'd like to do that separately from this change. If you could share additional details in how to setup for your scenario in #18 that'd make it easier to validate the LFS bits. Of course, please also feel free to submit a PR if you want to make the change.

File: src/GitStatusCache/src/Git.cpp [hunk 1]
```diff
@@ -270,6 +271,20 @@ bool Git::GetRefStatus(Git::Status& status, UniqueGitRepository& repository)
 		Log("Git.GetRefStatus.NoUpstream", Severity::Spam)
 			<< R"(Branch does not have a remote tracking reference. { "repositoryPath": ")" << status.RepositoryPath
 			<< R"(", "localBranch": ")" << status.Branch << R"(" })";
+
+		auto upstreamName = git_buf{ 0 };
+		result = git_branch_upstream_remote(
```
Comment (dahlbyk) [inline src/GitStatusCache/src/Git.cpp]: If I'm [reading correctly](https://github.com/libgit2/libgit2/blob/cb76eed5ce41c64607c4f99af947c79c493e8b7e/src/branch.c#L399-L422), this only checks `branch.{name}.remote`. Git doesn't consider an upstream to be valid without `branch.{name}.merge` also being set.

image

File: src/GitStatusCache/src/Git.cpp [hunk 2]
```diff
@@ -270,6 +271,20 @@ bool Git::GetRefStatus(Git::Status& status, UniqueGitRepository& repository)
 		Log("Git.GetRefStatus.NoUpstream", Severity::Spam)
```
Comment (cmarcusreid) [inline src/GitStatusCache/src/Git.cpp]: Hrm. I think I like it logged with the current behavior since we don't populate Upstream in this case. If we change that behavior to report the old Upstream details, I think your suggested adjustment makes sense.

File: src/GitStatusCache/src/Git.cpp (hunk 1 above)
Comment (cmarcusreid) [inline src/GitStatusCache/src/Git.cpp]: Seems reasonable. I'll tweak to check both. At that point I think we'll have all the information to populate the Upstream even if it's gone, so I'll adjust the log statement and I think I can revert the inversion on the posh-git change.

File: src/GitStatusCache/src/Git.cpp [hunk 3]
```diff
@@ -267,9 +268,46 @@ bool Git::GetRefStatus(Git::Status& status, UniqueGitRepository& repository)
 	result = git_branch_upstream(&upstream.get(), head.get());
 	if (result == GIT_ENOTFOUND)
 	{
-		Log("Git.GetRefStatus.NoUpstream", Severity::Spam)
-			<< R"(Branch does not have a remote tracking reference. { "repositoryPath": ")" << status.RepositoryPath
-			<< R"(", "localBranch": ")" << status.Branch << R"(" })";
+		auto upstreamRemoteName = git_buf{ 0 };
+		auto upstreamRemoteResult = git_branch_upstream_remote(
```
Comment (dahlbyk) [inline src/GitStatusCache/src/Git.cpp]: I don't think you need this now - `git_branch_upstream_name` includes a remote check.

Comment (cmarcusreid) [inline src/GitStatusCache/src/Git.cpp]: Thanks!
